version: '3.1'
services:
    database:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER:postgres
            POSTGRES_PASSWORD: kartik2703
            POSTGRES_DB: employee
        volumes:
          - data:/var/lib/postgresql/data

    myappli:
        build:
          context: .
          dockerfile: Dockerfile
        depends_on:
          - database
        volumes:
          - .:/code
        ports:
          - 8000:8000
volumes:
    data:
